# Main workflow, orchestrating and triggering other workflows
name: main

on:
  workflow_call: # be sure to use 'secrets: inherit' in the caller
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-code:
    uses: ./.github/workflows/test-code.yaml

  deploy-tools:
    # if: github.event.ref == 'refs/heads/main'
    needs: [test-code]
    uses: ./.github/workflows/tools-deploy.yaml
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      NAMESPACE_PREFIX: ${{ secrets.NAMESPACE_PREFIX }}

  deploy-metabase:
    # if: github.event.ref == 'refs/heads/main'
    needs: [test-code]
    uses: ./.github/workflows/metabase-deploy.yaml
    secrets:
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_METABASE_NAMESPACE: ${{ secrets.OPENSHIFT_METABASE_NAMESPACE }}
      HOST_ROUTE: ${{ secrets.HOST_ROUTE }}
      DB_ROUTE: ${{ secrets.DB_ROUTE }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
